Repository ita-social-projects/Home, pull requests merged in 2022-07, with the labels that each got.

#445 Fix error handling in Oauth Server
  home-oauth-server/src/main/java/com/softserveinc/ita/homeproject/homeoauthserver/service/OauthServiceImpl.java
  home-open-api/src/main/resources/yaml/oauth-openapi.yaml
Labels: bug

#459 Hotfix/issue#448 swagger error declaration examples
  home-open-api/src/main/resources/yaml/models/common.yaml
  home-open-api/src/main/resources/yaml/responses/responses.yaml
Labels: bug

#467 Issue #461. Bugfix branch added and documentation edited
  .github/workflows/Build_and_deploy_workflow.yml
  README.md
  home-docs/stages-of-development-and-versioning.md
Labels: documentation

#469 Feature/issue#441 invitations section address missing issue
  home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/invitations/InvitationApiIT.java
  home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/invitations/QueryInvitationIT.java
  home-application/src/main/java/com/softserveinc/ita/homeproject/application/api/CommonApi.java
  home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/cooperation/invitation/InvitationDto.java
  home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/cooperation/invitation/apartment/ApartmentInvitationDto.java
  home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/dto/user/role/RoleDto.java
  home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/service/cooperation/invitation/InvitationServiceImpl.java
  home-service/src/main/java/com/softserveinc/ita/homeproject/homeservice/service/general/email/SendCooperationEmailService.java
Labels: bug

#475 add testcase for weak password validation
  home-api-tests/src/test/java/com/softserveinc/ita/homeproject/api/tests/users/UserApiIT.java
Labels: bug, good first issue
